### ISSUE TITLE
Evaluation on BenchIE

### ISSUE THREAD

**Issue by bablf** [cgraywang/deepex#10]
An Evaluation on BenchIE would be great. Since it is probably the best available dataset. 

Link to Dataset: [https://paperswithcode.com/dataset/benchie](https://paperswithcode.com/dataset/benchie)

**Comment by Magolor** [comment]
Thank you for your kind advice. It is always welcomed to contribute and add more experiments and results.

**Comment by bablf** [comment]
sadly, I don't have 8 CUDA devices available 😄
