### ISSUE TITLE
Would script about model "Magolor/deepex-ranking-model" be released?

### ISSUE THREAD

**Issue by shengzhang37** [cgraywang/deepex#2]
Thank you for great work in zero-shot IE. Where can I find the related script about the pre-training about Magolor/deepex-ranking-model

**Comment by HaoyunHong** [comment]
@shengzhang37 Thanks very much for your interest! As we've mentioned in our README，we will release this script later.

**Comment by shengzhang37** [comment]
awesome! Thanks for reply.

**Comment by zhanwenchen** [comment]
@cgraywang @HaoyunHong @jesseLiu2000 When will this model be released?

**Comment by zhanwenchen** [comment]
Sorry this has indeed been released on https://huggingface.co/Magolor/deepex-ranking-model/tree/main. The path `Magolor/deepex-ranking-model` refers to the HuggingFace repo rather than a local directory.
