### ISSUE TITLE
Help running inference

### ISSUE THREAD

**Issue by adityakatta** [cgraywang/deepex#3]
Hi,
I am unable to figure out how to run OIE inference using the deepex models. Can you please help answering:
1) Where is the model
2) how to run OIE on the model
thanks,

**Comment by cgraywang** [comment]
Hi @adityakatta thanks for your interest! You should be able to run OIE following https://github.com/cgraywang/deepex#open-information-extraction. If you encounter any issues, could you please provide the error message? We could help to take a look, thanks!

**Comment by cgraywang** [comment]
Thanks @adityakatta . I will close the issue for now. If you still encounter the same issue, please free feel to reopen the issue.
