### ISSUE TITLE
About the reproduce results of deepex

### ISSUE THREAD

**Issue by EternalEep** [cgraywang/deepex#4]
Hi, thank you for your good work in OIE2016, but I use your default parameters with 1 V100 GPU, but I get the following results:

![image](https://user-images.githubusercontent.com/20923120/145673667-8bde8da2-0910-4cb8-aaed-815dfb9c02da.png)

Did I have some mistakes that I cannot get the 0.72 F1?

Also, I find that the constractive pretrain **deep-ranking-model** has not been released and the code is inference code now. It needs about 3 hours to test. Am I right?

Hope for your reply!

**Comment by HaoyunHong** [comment]
Hi @EternalEep thanks very much for your interest! We are taking a look at the reproduce mismatch issue.

The **deep-ranking-model** is released at https://huggingface.co/Magolor/deepex-ranking-model, which is shown in https://github.com/cgraywang/deepex/blob/a4a4cf60c96e1bfe3ddc8007498bf5ed783af730/scripts/ranking.py#L33 and you can directly use it in our code (with `transformers` package of huggingface).

The pretrain code of **deep-ranking-model** will be released later. Yes,  it needs 3 hours to test with 1 V100 GPU.

**Comment by EternalEep** [comment]
Thank you very much, I guess the problem of mismatch may be the environment, such as version of some packages.

**Comment by cgraywang** [comment]
@EternalEep Thanks, I will close the issue for now. If there are additional ones, please free feel to reach out.
