### ISSUE TITLE
关于OIE数据集中指标比较的疑惑

### ISSUE THREAD

**Issue by zzypeak** [cgraywang/deepex#6]
论文在Open Information Extraction任务中，在OIE2016数据集上deepex 的f1 =72.6，在附录中提到这是top3的指标，请教表格中其他方法如PropS、RnnOIE得到的指标使用的是top1还是top3？

![image](https://user-images.githubusercontent.com/6071020/151283415-5fdf099e-3052-42f4-9ca5-e6f96868694e.png)

**Comment by cgraywang** [comment]
Thanks for the interest @zzypeak . For PropS and RnnOIE, we strictly follow their implementation. For example, RnnOIE adopts a different approach compared to ours, which directly outputs the triples. Please feel free to let me know if there are additional issues.

**Comment by zzypeak** [comment]
Thanks for your sincerely apply. I think I should reimplement them by myself.
