### ISSUE TITLE
测试 Born in Glasgow, Fisher is a graduate of the London Opera Centre 生成三元组结果

### ISSUE THREAD

**Issue by zzypeak** [cgraywang/deepex#7]
使用论文中举的例子 ，”Born in Glasgow, Fisher is a graduate of the London Opera Centre. “ ，在第一步generator中抽取的三元组结果比较混乱，不知是否正常（OIE2016结果复现没有问题，top3 f1=72.6）。模型为默认的bert-large-cased。
[search_res.json.txt](https://github.com/cgraywang/deepex/files/7947193/search_res.json.txt)

**Comment by cgraywang** [comment]
Thanks for your interest @zzypeak . According to Table 3 (ablation study), the ranking model does improve the results significantly. We will also help to take a look at this particular case.

**Comment by zzypeak** [comment]
Thanks for your apply. Since it's an example of the paper, it should be a good case in my mind. Waiting for your result.

**Comment by Phevos75** [comment]
I run your code on my mac and lack many necessary files such as oie_readers.stanfordReader.@[cgraywang](https://github.com/cgraywang)
<img width="1712" alt="截屏2022-03-25 下午4 27 23" src="https://user-images.githubusercontent.com/26141935/160083219-5a3bbadd-e9a9-4dd5-8588-c6d71fb834f5.png">
This is because my run environment is wrong?

**Comment by Magolor** [comment]
> I run your code on my mac and lack many necessary files such as oie_readers.stanfordReader.@[cgraywang](https://github.com/cgraywang) <img alt="截屏2022-03-25 下午4 27 23" width="1712" src="https://user-images.githubusercontent.com/26141935/160083219-5a3bbadd-e9a9-4dd5-8588-c6d71fb834f5.png"> This is because my run environment is wrong?

Thank you for using. The requested files are all held in [this repo](https://github.com/gabrielStanovsky/supervised-oie), which is why you need to clone with `--recursive` argument to get the files used in submodules.

**Comment by Phevos75** [comment]
Hi,
It seems that the project misses the file of dist_wh_sbj_obj1.json in this repo <https://github.com/gabrielStanovsky/supervised-oie>, can you tell me how could I find it. 
Thanks!

**Comment by jesseliu0913** [comment]
Hi! I have run the program and now the code is fully operational.
