### ISSUE TITLE
Details of output from OIE_2016.sh

### ISSUE THREAD

**Issue by Metalchaos8527** [cgraywang/deepex#9]
Hello, thanks for your contribution to Open Information Extraction research.

I'm currently working on using your repo to create triples from the raw texts in Wikipedia by using your code.
~~~
bash tasks/OIE_2016.sh
~~~
I changed the data_dir to construct triples then executed the above code.
Code works fine, and it gave me the output called **search_res.json**.

The problem is, I can't find the description for the format of this output.
I can't find the keys for each value of this output. 
~~~
{"deduplicated:": {"Another Temporary Gallery [SEP] gallery [SEP] The Museum": [8, 0.7081716619431973, [[0, 25], [65, 75]], 27, 0] ...
~~~
For example, the thing I want to know is this list.
[8, 0.7081716619431973, [[0, 25], [65, 75]], 27, 0]
Coudl you briefly explain what each of this value mean?

**Comment by Magolor** [comment]
Hi! Thank you for asking. The code for this part is in `src/deepex/model/kgm.py`:
The first number is the frequency (it is not used I believe unless the score is averaged by frequency, according to the `dedup_ranking_type`),
the second number is the score (could have already been averaged),
the third item contains the subject and object span,
the fourth item is the attended length,
and the last is the offset (of the sentence to the whole document).

**Comment by Metalchaos8527** [comment]
Thank you very much for your kind reply!
I'll close this issue
